# Generated by Django 4.0.4 on 2022-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
