# Generated by Django 4.0.4 on 2022-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_note_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['complete']},
        ),
    ]
