# Generated by Django 4.0.4 on 2022-06-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.group'),
        ),
    ]
